import type { Metadata } from "next";
import { geistSans } from "@/lib/font";
import "@/style/index.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "MOOX - Recommedation Movies Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
